import { getDimensionStream } from '../facebook/dimension.service';
import { getInsightsStream } from '../facebook/insights.service';
import { DateField, IDField, NumericField, StringField, RecordField, TimestampField } from './pipeline.schema';
import { createInsightsPipeline, createDimensionsPipeline } from './pipeline.interface';

const ActionsBreakdownFields = [new StringField('action_type'), new NumericField('value')];

export const AdsPublisherPlatformInsights = createInsightsPipeline({
    name: 'AdsPublisherPlatformInsights',
    extractStream: getInsightsStream({
        level: 'ad',
        breakdowns: 'publisher_platform',
        fields: [
            'date_start',
            'date_stop',
            'account_id',
            'campaign_id',
            'campaign_name',
            'adset_id',
            'adset_name',
            'ad_id',
            'ad_name',
            'actions',
            'action_values',
            'clicks',
            'cpc',
            'cpm',
            'ctr',
            'frequency',
            'impressions',
            'inline_link_click_ctr',
            'inline_link_clicks',
            'reach',
            'spend',
        ],
    }),
    fields: [
        new DateField('date_start'),
        new DateField('date_stop'),
        new IDField('account_id'),
        new StringField('publisher_platform'),
        new IDField('campaign_id'),
        new StringField('campaign_name'),
        new IDField('adset_id'),
        new StringField('adset_name'),
        new IDField('ad_id'),
        new StringField('ad_name'),
        new NumericField('clicks'),
        new NumericField('cpc'),
        new NumericField('cpm'),
        new NumericField('ctr'),
        new NumericField('frequency'),
        new NumericField('impressions'),
        new NumericField('inline_link_click_ctr'),
        new NumericField('inline_link_clicks'),
        new NumericField('reach'),
        new NumericField('spend'),
        new RecordField('actions', ActionsBreakdownFields, true),
        new RecordField('action_values', ActionsBreakdownFields, true),
        new TimestampField('_batched_at'),
    ],
});

export const CampaignsDevicePlatformPositionInsights = createInsightsPipeline({
    name: 'CampaignsDevicePlatformPositionInsights',
    extractStream: getInsightsStream({
        level: 'campaign',
        breakdowns: 'device_platform,publisher_platform,platform_position',
        fields: [
            'date_start',
            'date_stop',
            'account_id',
            'campaign_id',
            'campaign_name',
            'actions',
            'action_values',
            'clicks',
            'cpc',
            'cpm',
            'ctr',
            'frequency',
            'impressions',
            'inline_link_click_ctr',
            'inline_link_clicks',
            'reach',
            'spend',
        ],
    }),
    fields: [
        new DateField('date_start'),
        new DateField('date_stop'),
        new IDField('account_id'),
        new StringField('device_platform'),
        new StringField('publisher_platform'),
        new StringField('platform_position'),
        new IDField('campaign_id'),
        new StringField('campaign_name'),
        new NumericField('clicks'),
        new NumericField('cpc'),
        new NumericField('cpm'),
        new NumericField('ctr'),
        new NumericField('frequency'),
        new NumericField('impressions'),
        new NumericField('inline_link_click_ctr'),
        new NumericField('inline_link_clicks'),
        new NumericField('reach'),
        new NumericField('spend'),
        new RecordField('actions', ActionsBreakdownFields, true),
        new RecordField('action_values', ActionsBreakdownFields, true),
        new TimestampField('_batched_at'),
    ],
});

export const CampaignsCountryInsights = createInsightsPipeline({
    name: 'CampaignsCountryInsights',
    extractStream: getInsightsStream({
        level: 'campaign',
        breakdowns: 'country',
        fields: [
            'date_start',
            'date_stop',
            'account_id',
            'campaign_id',
            'campaign_name',
            'actions',
            'action_values',
            'clicks',
            'cpc',
            'cpm',
            'ctr',
            'frequency',
            'impressions',
            'inline_link_click_ctr',
            'inline_link_clicks',
            'reach',
            'spend',
        ],
    }),
    fields: [
        new DateField('date_start'),
        new DateField('date_stop'),
        new IDField('account_id'),
        new StringField('country'),
        new IDField('campaign_id'),
        new StringField('campaign_name'),
        new NumericField('clicks'),
        new NumericField('cpc'),
        new NumericField('cpm'),
        new NumericField('ctr'),
        new NumericField('frequency'),
        new NumericField('impressions'),
        new NumericField('inline_link_click_ctr'),
        new NumericField('inline_link_clicks'),
        new NumericField('reach'),
        new NumericField('spend'),
        new RecordField('actions', ActionsBreakdownFields, true),
        new RecordField('action_values', ActionsBreakdownFields, true),
        new TimestampField('_batched_at'),
    ],
});

export const CampaignsRegionInsights = createInsightsPipeline({
    name: 'CampaignsRegionInsights',
    extractStream: getInsightsStream({
        level: 'campaign',
        breakdowns: 'region',
        fields: [
            'date_start',
            'date_stop',
            'account_id',
            'campaign_id',
            'campaign_name',
            'actions',
            'action_values',
            'clicks',
            'cpc',
            'cpm',
            'ctr',
            'frequency',
            'impressions',
            'inline_link_click_ctr',
            'inline_link_clicks',
            'reach',
            'spend',
        ],
    }),
    fields: [
        new DateField('date_start'),
        new DateField('date_stop'),
        new IDField('account_id'),
        new StringField('region'),
        new IDField('campaign_id'),
        new StringField('campaign_name'),
        new NumericField('clicks'),
        new NumericField('cpc'),
        new NumericField('cpm'),
        new NumericField('ctr'),
        new NumericField('frequency'),
        new NumericField('impressions'),
        new NumericField('inline_link_click_ctr'),
        new NumericField('inline_link_clicks'),
        new NumericField('reach'),
        new NumericField('spend'),
        new RecordField('actions', ActionsBreakdownFields, true),
        new RecordField('action_values', ActionsBreakdownFields, true),
        new TimestampField('_batched_at'),
    ],
});

export const CampaignsAgeGenderInsights = createInsightsPipeline({
    name: 'CampaignsAgeGenderInsights',
    extractStream: getInsightsStream({
        level: 'campaign',
        breakdowns: 'age,gender',
        fields: [
            'date_start',
            'date_stop',
            'account_id',
            'campaign_id',
            'campaign_name',
            'actions',
            'action_values',
            'clicks',
            'cpc',
            'cpm',
            'ctr',
            'frequency',
            'impressions',
            'inline_link_click_ctr',
            'inline_link_clicks',
            'reach',
            'spend',
        ],
    }),
    fields: [
        new DateField('date_start'),
        new DateField('date_stop'),
        new IDField('account_id'),
        new StringField('age'),
        new StringField('gender'),
        new IDField('campaign_id'),
        new StringField('campaign_name'),
        new NumericField('clicks'),
        new NumericField('cpc'),
        new NumericField('cpm'),
        new NumericField('ctr'),
        new NumericField('frequency'),
        new NumericField('impressions'),
        new NumericField('inline_link_click_ctr'),
        new NumericField('inline_link_clicks'),
        new NumericField('reach'),
        new NumericField('spend'),
        new RecordField('actions', ActionsBreakdownFields, true),
        new RecordField('action_values', ActionsBreakdownFields, true),
        new TimestampField('_batched_at'),
    ],
});

export const Ads = createDimensionsPipeline({
    name: 'Ads',
    extractStream: getDimensionStream({
        endpoint: 'ads',
        fields: ['id', 'preview_shareable_link'],
    }),
    fields: [new IDField('id'), new StringField('preview_shareable_link')],
});
